repos:
  - repo: https://github.com/psf/black
    rev: "21.6b0"
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        additional_dependencies: [darglint]
  - repo: https://github.com/pycqa/isort
    rev: "5.9.1"
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy # TODO: use official version
    rev: "v0.910"
    hooks:
      - id: mypy
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
