---
# Example ModificationGenerator settings file
modifications_chains:
  - share: 0.25
    modifications:
      - name: GammaCorrectionModification
        options:
          gamma_value: 0.75
      - name: CLAHEModification
        options:
          clip_limit: 2.0
          grid_width: 8
          grid_height: 8
  - share: 0.25
    modifications:
      - name: GammaCorrectionModification
        options:
          gamma_value: 0.75
      - name: HistogramEqualizationModification
